In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Bengkulu,ID,2020-10-19 17:00:36,-3.80,102.27,76.55,88,94,3.56
1,1,Asau,RO,2020-10-19 17:01:04,46.43,26.40,50.00,61,2,11.41
2,2,Puerto Ayora,EC,2020-10-19 17:01:04,-0.74,-90.35,77.00,69,75,9.17
3,3,New Norfolk,AU,2020-10-19 17:01:04,-42.78,147.06,42.01,80,39,2.33
4,4,Aksu,CN,2020-10-19 17:01:05,41.12,80.26,51.78,41,0,1.16

In [3]:
# Check data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of windiness
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 80
What is the maximum temperature you would like for your trip? 81

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
#preferred_cities_df.head(10)

In [12]:
preferred_cities_df.count()

City_ID       26
City          26
Country       26
Date          26
Lat           26
Lng           26
Max Temp      26
Humidity      26
Cloudiness    26
Wind Speed    26
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

                         City Country  Max Temp    Lat     Lng Hotel Name
26                      Hobyo      SO     80.17   5.35   48.53
28            Arraial Do Cabo      BR     80.60 -22.97  -42.03
111                 Tamandare      BR     80.67  -8.76  -35.10
133                   Ternate      ID     80.98   0.80  127.40
142                  Maragogi      BR     80.17  -9.01  -35.22
153                   Bulembu      SZ     81.00 -25.97   31.13
154                  Tevaitoa      PF     80.26 -16.78 -151.50
201             Guia De Isora      ES     81.00  28.21  -16.78
203                       Sur      OM     80.83  22.57   59.53
271                  Paracuru      BR     81.00  -3.41  -39.03
281                 Namatanai      PG     80.37  -3.67  152.43
302                Port Blair      IN     80.89  11.67   92.75
348                Hambantota      LK     80.58   6.12   81.12
350                 Port Said      EG     80.60  31.26   32.28
356                      Chuy      UY     80.96 -33.70  -53.46
360                  Takoradi      GH     80.33   4.88   -1.76
392  Sao Jose Da Coroa Grande      BR     80.40  -8.90  -35.15
396                    Awbari      LY     80.42  26.59   12.78
436                    Rincon      US     80.01  32.30  -81.24
440                    Jaipur      IN     80.60  26.92   75.82
450                   Estelle      US     80.01  29.85  -90.11
462                   Aguimes      ES     80.60  27.91  -15.45
499                 Tenosique      MX     80.60  17.48  -91.43
518                    Afikpo      NG     80.67   5.89    7.94
527                   Vaitape      PF     80.64 -16.52 -151.75
570                 Pemangkat      ID     80.56   1.17  108.97

In [19]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print("FuckShitStak")
    except (IndexError):
        print("Hotel not found... skipping.")

FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak
FuckShitStak

In [18]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
26,Hobyo,SO,80.17,5.35,48.53,Osmani Hotel
28,Arraial Do Cabo,BR,80.60,-22.97,-42.03,Pousada Porto Praia
111,Tamandare,BR,80.67,-8.76,-35.10,Pousada 100 Passos
133,Ternate,ID,80.98,0.80,127.40,Grand Dafam Bela Ternate
142,Maragogi,BR,80.17,-9.01,-35.22,Salinas do Maragogi All Inclusive Resort
153,Bulembu,SZ,81.00,-25.97,31.13,Bulembu Lodge
154,Tevaitoa,PF,80.26,-16.78,-151.50,Hôtel Raiatea Lodge
201,Guia De Isora,ES,81.00,28.21,-16.78,La Vista Pension
203,Sur,OM,80.83,22.57,59.53,Sur Plaza Hotel
271,Paracuru,BR,81.00,-3.41,-39.03,Hotel Vento Brasil
281,Namatanai,PG,80.37,-3.67,152.43,Namatanai Hotel
302,Port Blair,IN,80.89,11.67,92.75,Fortune Resort Bay Island
348,Hambantota,LK,80.58,6.12,81.12,Bungalow 63
350,Port Said,EG,80.60,31.26,32.28,Aracan Hotel
356,Chuy,UY,80.96,-33.70,-53.46,Nuevo Hotel Plaza
360,Takoradi,GH,80.33,4.88,-1.76,Raybow International Hotel
392,Sao Jose Da Coroa Grande,BR,80.40,-8.90,-35.15,Crôa Mares Hotel
396,Awbari,LY,80.42,26.59,12.78,فندق أوباري
436,Rincon,US,80.01,32.30,-81.24,Bent tree subdivision
440,Jaipur,IN,80.60,26.92,75.82,Hotel Kalyan
450,Estelle,US,80.01,29.85,-90.11,Comfort Inn Marrero - New Orleans West
462,Aguimes,ES,80.60,27.91,-15.45,Hotel Villa de Aguimes
499,Tenosique,MX,80.60,17.48,-91.43,Hotel Central
518,Afikpo,NG,80.67,5.89,7.94,P. Noble Hotels and Suite
527,Vaitape,PF,80.64,-16.52,-151.75,Conrad Bora Bora Nui
570,Pemangkat,ID,80.56,1.17,108.97,Kost H.Syamsuddin

In [20]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))